import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LoL Guesser",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <script
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={{
            __html: `
                (function () {
                  var msg = '🚨  CHEATER! Get out of here 🚨';
                  document.body.prepend(document.createComment(' ' + msg + ' '));
                })();
              `,
          }}
        />
        {children}
      </body>
    </html>
  );
}
